### ISSUE TITLE
[BUG] "human_confidence" property does not return value

### ISSUE THREAD

**Issue by KristynaJanku** [Tlaloc-Es/pypose#9]
**Issue description**
"human_confidence" property of "YoloV7PoseKeypoints" class in "aipose/models/yolov7/domain.py" does not return the confidence value and causes indexing error.

**Steps to reproduce**
Access "human_confidence" property on "YoloV7PoseKeypoints" instance.

**Expected behavior**
Return human confidence value.

**Actual behavior**
No returned value and indexing error.

**Environment**
- Python version: 3.10
- Library version: 3.0.0
- Operating system: Ubuntu 20

**Additional context**
The current code is missing return statement and causes indexing error.
```
@property
    def human_confidence(self) -> List[float]:
        self.raw_keypoints[YoloV7PoseKeypointsIndex.CONFIDENCE]
```
Adding "return" and ".value" for the index gives the proper human confidence value and fixes indexing error:
```
@property
    def human_confidence(self) -> List[float]:
        return self.raw_keypoints[YoloV7PoseKeypointsIndex.CONFIDENCE.value]
```

**Comment by Tlaloc-Es** [comment]
Hi @KristynaJanku,
Thank you for reporting the bug. I’ve just launched a release with the fix. Feel free to submit a PR next time if you’d like.

Kind regards,
